import { z } from "zod";

export const DiseaseFormDataSchema = z.object({
  patientId: z.string().nonempty("ID is required"),
  lastname: z.string().nonempty("Last name is required"),
  email: z.string().email("Invalid email format"),
  primary_site: z.string().nonempty("Primary site is required"),
  date_of_diagnosis: z.string().nonempty("Date of diagnosis is required"),
  basis_of_diagnosis: z.string().nullable(),
  basis_of_diagnosis_option: z.string().nonempty("Basis of diagnosis is required"),
  basis_of_diagnosis_suboption: z.string().nonempty("Basis of diagnosis is required"),
  laterality: z.string().optional(),
  histo_pathology: z.string().nonempty("Pathology is required"),
  histo_tumorSize: z.string().optional(),
  histo_tumorExtension: z.string().optional(),
  histo_tumorGrade: z.string().optional(),
  histo_nodePositive: z.string().optional(),
  histo_nodeHarvest: z.string().optional(),
  histo_negativeMargins: z.string().optional(),
  histo_stage: z.string().optional(),
  histo_positiveMargins: z.string().optional(),
  disease_extent: z.string().optional(),
  disease_tumor_size: z.string().optional(),
  disease_lymph_node: z.string().optional(),
  disease_metastatic: z.string().optional(),
  metastatic_distant_ln: z.string().optional(),
  metastatic_bone: z.string().optional(),
  metastatic_liver: z.string().optional(),
  metastatic_lung: z.string().optional(),
  metastatic_brain: z.string().optional(),
  metastatic_ovary: z.string().optional(),
  metastatic_skin: z.string().optional(),
  metastatic_intestine: z.string().optional(),
  metastatic_others: z.string().optional(),
  metastatic_unknown: z.string().optional(),
  metastatic_notes: z.string().optional(),
  multiple_primaries: z.array(z.string()).optional(),
  stage: z.string().optional(),
  stage_type: z.string().optional(),
  disease_tstage: z.string().optional(),
  disease_nstage: z.string().optional(),
  disease_mstage: z.string().optional(),
  disease_gstage: z.string().optional(),
  dxstatus_alive: z.string().optional(),
  dxstatus_symptoms: z.string().optional(),
  dxstatus_recurrence: z.string().optional(),
  dxstatus_metastatic: z.string().optional(),
  dxstatus_curative: z.string().optional(),
  disease_encoder: z.string().optional(),
});

export const DiseaseErrorsSchema = z.object({
  lastname: z.string().optional(),
  email: z.string().optional(),
  primary_site: z.string().optional(),
  date_of_diagnosis: z.string().optional(),
  basis_of_diagnosis: z.string().optional(),
  basis_of_diagnosis_option: z.string().optional(),
  basis_of_diagnosis_suboption: z.string().optional(),
  laterality: z.string().optional(),
  histo_pathology: z.string().optional(),
  histo_tumorSize: z.string().optional(),
  histo_tumorExtension: z.string().optional(),
  histo_tumorGrade: z.string().optional(),
  histo_nodePositive: z.string().optional(),
  histo_nodeHarvest: z.string().optional(),
  histo_negativeMargins: z.string().optional(),
  histo_stage: z.string().optional(),
  histo_positiveMargins: z.string().optional(),
  disease_extent: z.string().optional(),
  disease_tumor_size: z.string().optional(),
  disease_lymph_node: z.string().optional(),
  disease_metastatic: z.string().optional(),
  metastatic_distant_ln: z.string().optional(),
  metastatic_bone: z.string().optional(),
  metastatic_liver: z.string().optional(),
  metastatic_lung: z.string().optional(),
  metastatic_brain: z.string().optional(),
  metastatic_ovary: z.string().optional(),
  metastatic_skin: z.string().optional(),
  metastatic_intestine: z.string().optional(),
  metastatic_others: z.string().optional(),
  metastatic_unknown: z.string().optional(),
  metastatic_notes: z.string().optional(),
  multiple_primaries: z.string().optional(),
  stage: z.string().optional(),
  stage_type: z.string().optional(),
  disease_tstage: z.string().optional(),
  disease_nstage: z.string().optional(),
  disease_mstage: z.string().optional(),
  disease_gstage: z.string().optional(),
  dxstatus_alive: z.string().optional(),
  dxstatus_symptoms: z.string().optional(),
  dxstatus_recurrence: z.string().optional(),
  dxstatus_metastatic: z.string().optional(),
  dxstatus_curative: z.string().optional(),
  disease_encoder: z.string().optional(),
});

export type FormData = z.infer<typeof DiseaseFormDataSchema>;
export type Errors = z.infer<typeof DiseaseErrorsSchema>;
